### ISSUE TITLE
Extra `"` in L402 challenge headers?

### ISSUE THREAD

**Issue by positiveblue** [sulusolutions/l402-ts#10]
This library tries to (rightly!) match the formant from [the spec draft](https://github.com/lightning/blips/pull/26#discussion_r1605598764)

`402 macaroon="{macaroon}", invoice="{invoice}"`

However, I think this is a typo in the draft we should go with the version without the `"` surrounding the string values.

Your input is very much welcomed in the spec discussion :+1:

**Comment by SamuelAl** [comment]
Hi @positiveblue , thanks for mentioning this! I added my response to the L402 BLIP draft [here](https://github.com/lightning/blips/pull/26#discussion_r1606489837)

TLDR: I think you are referring to two different things. The WWW-Authenticate header does typically enclose values in double quotes as can be seen in other auth schemes (more details in the BLIP draft). I therefore think that it is correct to also use them in the L402 challenge header, as is specified in the L402 spec.

Happy to continue the conversation in the BLIP draft, but since the current functionality is in keeping with the spec I will close the issue for now. We can always reopen it depending on the decision arrived to in the draft.
